#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.3 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Feb 07 21:09:51 CST 2018
# SW Build 2018833 on Wed Oct  4 19:58:07 MDT 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim axi_vip_0_exdes_adv_mst_active__pt_passive__slv_comb_behav -key {Behavioral:sim_adv_mst_active__pt_passive__slv_comb:Functional:axi_vip_0_exdes_adv_mst_active__pt_passive__slv_comb} -tclbatch axi_vip_0_exdes_adv_mst_active__pt_passive__slv_comb.tcl -log simulate.log
