# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bram_test_axi_smc_0.xci
# IP: The module: 'bram_test_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/bd_d660.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_54/bd_d660_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_60/bd_d660_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_67/bd_d660_m01s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_74/bd_d660_m02s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_81/bd_d660_m03s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_87/bd_d660_m03e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_82/bd_d660_m03arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_83/bd_d660_m03rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_84/bd_d660_m03awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_85/bd_d660_m03wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_86/bd_d660_m03bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_80/bd_d660_m02e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_75/bd_d660_m02arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_76/bd_d660_m02rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_77/bd_d660_m02awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_78/bd_d660_m02wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_79/bd_d660_m02bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_73/bd_d660_m01e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_68/bd_d660_m01arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_69/bd_d660_m01rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_70/bd_d660_m01awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_71/bd_d660_m01wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_72/bd_d660_m01bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_66/bd_d660_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_61/bd_d660_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_62/bd_d660_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_63/bd_d660_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_64/bd_d660_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_65/bd_d660_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_55/bd_d660_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_56/bd_d660_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_57/bd_d660_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_58/bd_d660_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_59/bd_d660_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_51/bd_d660_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_52/bd_d660_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_53/bd_d660_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_46/bd_d660_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_47/bd_d660_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_48/bd_d660_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_49/bd_d660_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_50/bd_d660_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_44/bd_d660_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_45/bd_d660_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_54/bd_d660_s00a2s_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_60/bd_d660_m00s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_67/bd_d660_m01s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_74/bd_d660_m02s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_81/bd_d660_m03s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_82/bd_d660_m03arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_83/bd_d660_m03rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_84/bd_d660_m03awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_85/bd_d660_m03wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_86/bd_d660_m03bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_75/bd_d660_m02arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_76/bd_d660_m02rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_77/bd_d660_m02awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_78/bd_d660_m02wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_79/bd_d660_m02bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_68/bd_d660_m01arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_69/bd_d660_m01rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_70/bd_d660_m01awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_71/bd_d660_m01wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_72/bd_d660_m01bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_61/bd_d660_m00arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_62/bd_d660_m00rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_63/bd_d660_m00awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_64/bd_d660_m00wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_65/bd_d660_m00bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_55/bd_d660_sarn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_56/bd_d660_srn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_57/bd_d660_sawn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_58/bd_d660_swn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_59/bd_d660_sbn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_46/bd_d660_arsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_47/bd_d660_rsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_48/bd_d660_awsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_49/bd_d660_wsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_50/bd_d660_bsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_45/bd_d660_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_45/bd_d660_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bram_test_axi_smc_0.xci
# IP: The module: 'bram_test_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/bd_d660.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_54/bd_d660_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_60/bd_d660_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_67/bd_d660_m01s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_74/bd_d660_m02s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_81/bd_d660_m03s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_87/bd_d660_m03e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_82/bd_d660_m03arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_83/bd_d660_m03rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_84/bd_d660_m03awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_85/bd_d660_m03wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_86/bd_d660_m03bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_80/bd_d660_m02e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_75/bd_d660_m02arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_76/bd_d660_m02rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_77/bd_d660_m02awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_78/bd_d660_m02wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_79/bd_d660_m02bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_73/bd_d660_m01e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_68/bd_d660_m01arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_69/bd_d660_m01rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_70/bd_d660_m01awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_71/bd_d660_m01wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_72/bd_d660_m01bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_66/bd_d660_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_61/bd_d660_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_62/bd_d660_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_63/bd_d660_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_64/bd_d660_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_65/bd_d660_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_55/bd_d660_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_56/bd_d660_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_57/bd_d660_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_58/bd_d660_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_59/bd_d660_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_51/bd_d660_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_52/bd_d660_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_53/bd_d660_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_46/bd_d660_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_47/bd_d660_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_48/bd_d660_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_49/bd_d660_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_50/bd_d660_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_44/bd_d660_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_45/bd_d660_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_54/bd_d660_s00a2s_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_60/bd_d660_m00s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_67/bd_d660_m01s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_74/bd_d660_m02s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_81/bd_d660_m03s2a_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_82/bd_d660_m03arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_83/bd_d660_m03rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_84/bd_d660_m03awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_85/bd_d660_m03wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_86/bd_d660_m03bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_75/bd_d660_m02arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_76/bd_d660_m02rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_77/bd_d660_m02awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_78/bd_d660_m02wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_79/bd_d660_m02bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_68/bd_d660_m01arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_69/bd_d660_m01rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_70/bd_d660_m01awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_71/bd_d660_m01wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_72/bd_d660_m01bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_61/bd_d660_m00arn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_62/bd_d660_m00rn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_63/bd_d660_m00awn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_64/bd_d660_m00wn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_65/bd_d660_m00bn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_55/bd_d660_sarn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_56/bd_d660_srn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_57/bd_d660_sawn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_58/bd_d660_swn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_59/bd_d660_sbn_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_46/bd_d660_arsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_47/bd_d660_rsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_48/bd_d660_awsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_49/bd_d660_wsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_50/bd_d660_bsw_1_ooc.xdc

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_45/bd_d660_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/bd_0/ip/ip_45/bd_d660_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.srcs/sources_1/bd/bram_test/ip/bram_test_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_test_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
