webtalk_init -webtalk_dir /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/bram_test_wrapper_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 13 19:35:05 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018833" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210777625_1777494353_210565950_607" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "70e23a72-2140-459d-a422-40545ea070f9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "40fdc0be19a045ce96933dfe089bb2f1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS release 6.9 (Final)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1600.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "101.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.29_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "195800_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2763557907 -regid "210777625_1777494353_210565950_607" -xml /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/bram_test_wrapper_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/bram_test_wrapper_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ecelrc/students/agroszewski/arch18/vivado/lab1/lab1.sim/sim_1/behav/xsim/xsim.dir/bram_test_wrapper_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
