# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/bram_test/bram_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test || ORIG_REF_NAME==bram_test} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_processing_system7_0_0/bram_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_processing_system7_0_0 || ORIG_REF_NAME==bram_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_blk_mem_gen_0_0/bram_test_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_blk_mem_gen_0_0 || ORIG_REF_NAME==bram_test_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_axi_bram_ctrl_0_0/bram_test_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_axi_bram_ctrl_0_0 || ORIG_REF_NAME==bram_test_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_axi_bram_ctrl_1_0/bram_test_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_axi_bram_ctrl_1_0 || ORIG_REF_NAME==bram_test_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_axi_gpio_0_0/bram_test_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_axi_gpio_0_0 || ORIG_REF_NAME==bram_test_axi_gpio_0_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_axi_smc_0/bram_test_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_axi_smc_0 || ORIG_REF_NAME==bram_test_axi_smc_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_rst_ps7_0_100M_0/bram_test_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_rst_ps7_0_100M_0 || ORIG_REF_NAME==bram_test_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/bram_test/ip/bram_test_LFSR_beta_0_0/bram_test_LFSR_beta_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_test_LFSR_beta_0_0 || ORIG_REF_NAME==bram_test_LFSR_beta_0_0} -quiet] -quiet

# XDC: bd/bram_test/bram_test_ooc.xdc
